# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, b'pending'), (1, b'published'), (2, b'deleted')], default=0),
        ),
        migrations.AddField(
            model_name='foreignrelation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, b'pending'), (1, b'published'), (2, b'deleted')], default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, b'pending'), (1, b'published'), (2, b'deleted')], default=0),
        ),
        migrations.AddField(
            model_name='relation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, b'pending'), (1, b'published'), (2, b'deleted')], default=0),
        ),
    ]
