# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 11:47
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Concept = apps.get_model("thesaurus", "Concept")
    Version = apps.get_model("thesaurus", "Version")
    db_alias = schema_editor.connection.alias
    try:
        latest_concept = Concept.objects.using(db_alias).latest('date_changed')
    except Concept.DoesNotExist:
        return
    Version.objects.create(
        identifier="2.0",  # This identifier will probably change
        publication_date=latest_concept.date_changed,
        is_current=True,
    )


def reverse_func(apps, schema_editor):
    # No need to delete initial version, it gets deleted once with the table
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0003_add_pending_retired_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('changed_note', models.TextField()),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
