# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-13-03 16:00
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Version = apps.get_model("thesaurus", "Version")
    Version.objects.create(
        is_current=False,
    )


def reverse_func(apps, schema_editor):
    Version = apps.get_model("thesaurus", "Version")
    db_alias = schema_editor.connection.alias
    try:
        version = Version.objects.using(db_alias).get(identifier="")
        version.delete()
    except Version.DoesNotExist:
        return


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0005_add_fk_to_version'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
