# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:12
from __future__ import unicode_literals

from django.db import migrations
import gemet.thesaurus.models


class Migration(migrations.Migration):

    dependencies = [
        ("thesaurus", "0006_add_version_without_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditableGroup",
            fields=[],
            options={
                "proxy": True,
            },
            bases=(gemet.thesaurus.models.EditMixin, "thesaurus.group"),
        ),
        migrations.CreateModel(
            name="EditableSuperGroup",
            fields=[],
            options={
                "proxy": True,
            },
            bases=(gemet.thesaurus.models.EditMixin, "thesaurus.supergroup"),
        ),
        migrations.CreateModel(
            name="EditableTerm",
            fields=[],
            options={
                "proxy": True,
            },
            bases=(gemet.thesaurus.models.EditMixin, "thesaurus.term"),
        ),
        migrations.CreateModel(
            name="EditableTheme",
            fields=[],
            options={
                "proxy": True,
            },
            bases=(gemet.thesaurus.models.EditMixin, "thesaurus.theme"),
        ),
    ]
