# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0010_asynctask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definitionsource',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='definitionsource',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='definitionsource',
            name='publication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='definitionsource',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='definitionsource',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='definitionsource',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
