# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-01-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0011_auto_20170628_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spreadsheet', models.FileField(help_text=u'Details about the supported file format can be found <a href="https://taskman.eionet.europa.eu/projects/infrastructure/wiki/Importing_new_concepts_in_GEMET">here</a>.', upload_to=u'imports/')),
                ('started_at', models.DateTimeField(null=True)),
                ('failed_at', models.DateTimeField(null=True)),
                ('succeeded_at', models.DateTimeField(null=True)),
                ('logs', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
