# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-01-18 09:46
from __future__ import unicode_literals

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Concept = apps.get_model("thesaurus", "Concept")
    Property = apps.get_model("thesaurus", "Property")
    Relation = apps.get_model("thesaurus", "Relation")
    ForeignRelation = apps.get_model("thesaurus", "ForeignRelation")
    str_values = {
        0: 'pending',
        1: 'published',
        2: 'deleted',
        3: 'deleted_pending',
    }
    db_alias = schema_editor.connection.alias
    for Model in [Concept, Property, Relation, ForeignRelation]:
        for int_value, str_value in str_values.items():
            Model.objects.using(db_alias).filter(status=int_value).update(
                string_status=str_value
            )


def reverse_func(apps, schema_editor):
    Concept = apps.get_model("thesaurus", "Concept")
    Property = apps.get_model("thesaurus", "Property")
    Relation = apps.get_model("thesaurus", "Relation")
    ForeignRelation = apps.get_model("thesaurus", "ForeignRelation")
    int_values = {
        'pending': 0,
        'published': 1,
        'deleted': 2,
        'deleted_pending': 3,
    }
    db_alias = schema_editor.connection.alias
    for Model in [Concept, Property, Relation, ForeignRelation]:
        for str_value, int_value in int_values.items():
            Model.objects.using(db_alias).filter(
                string_status=str_value
            ).update(status=int_value)


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0013_timetrack_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='string_status',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'published', b'published'), (b'deleted', b'deleted'), (b'deleted_pending', b'deleted pending')], default=b'pending', max_length=64),
        ),
        migrations.AddField(
            model_name='foreignrelation',
            name='string_status',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'published', b'published'), (b'deleted', b'deleted'), (b'deleted_pending', b'deleted pending')], default=b'pending', max_length=64),
        ),
        migrations.AddField(
            model_name='property',
            name='string_status',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'published', b'published'), (b'deleted', b'deleted'), (b'deleted_pending', b'deleted pending')], default=b'pending', max_length=64),
        ),
        migrations.AddField(
            model_name='relation',
            name='string_status',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'published', b'published'), (b'deleted', b'deleted'), (b'deleted_pending', b'deleted pending')], default=b'pending', max_length=64),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='concept',
            name='status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='foreignrelation',
            name='status',
        ),
        migrations.RenameField(
            model_name='concept',
            old_name='string_status',
            new_name='status'
        ),
        migrations.RenameField(
            model_name='property',
            old_name='string_status',
            new_name='status'
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='string_status',
            new_name='status'
        ),
        migrations.RenameField(
            model_name='foreignrelation',
            old_name='string_status',
            new_name='status'
        ),
    ]
