from django.conf.urls import patterns, url, include

from .views import (
    redirect_old_urls,
    concept_redirect,
    old_concept_redirect,
    download,
    AboutView,
    ThemesView,
    GroupsView,
    DefinitionSourcesView,
    AlphabetsView,
    SearchView,
    RelationsView,
    TermView,
    ThemeView,
    GroupView,
    SuperGroupView,
    ThemeConceptsView,
    AlphabeticView,
    BackboneView,
    BackboneRDFView,
    DefinitionsView,
    GemetGroupsView,
    GemetRelationsView,
    DefinitionsByLanguage,
    GroupsByLanguage,
    GemetThesaurus,
)
from .api import ApiView


urlpatterns = patterns(
    '',
    url(r'^$', ThemesView.as_view()),
    url(r'^gemet/$', ApiView.as_view(), name='api_root'),
    url(r'^(?P<langcode>[a-zA-Z-]+)/', include([
        url(r'^about/$', AboutView.as_view(), name='about'),
        url(r'^themes/$', ThemesView.as_view(), name='themes'),
        url(r'^groups/$', GroupsView.as_view(), name='groups'),
        url(r'^concept/(?P<concept_id>\d+)/$', TermView.as_view(),
            name='concept'),
        url(r'^theme/(?P<concept_id>\d+)/$', ThemeView.as_view(),
            name='theme'),
        url(r'^group/(?P<concept_id>\d+)/$', GroupView.as_view(),
            name='group'),
        url(r'^supergroup/(?P<concept_id>\d+)/$', SuperGroupView.as_view(),
            name='supergroup'),
        url(r'^relations/(?P<group_id>\d+)/$', RelationsView.as_view(),
            name='relations'),
        url(r'^theme/(?P<theme_id>\d+)/concepts/$',
            ThemeConceptsView.as_view(),
            name='theme_concepts'
            ),
        url(r'^alphabetic/$', AlphabeticView.as_view(), name='alphabetic'),
        url(r'^alphabets/$', AlphabetsView.as_view(), name='alphabets'),
        url(r'^search/$', SearchView.as_view(), name='search'),
        url(r'^definition_sources/$', DefinitionSourcesView.as_view(),
            name='definition_sources'),
        url(r'^rdf/$', download, name='download'),
        url(r'^gemet-definitions.rdf/$', DefinitionsByLanguage.as_view(),
            name='language_definitions'),
        url(r'^gemet-groups.rdf/$', GroupsByLanguage.as_view(),
            name='language_groups'),
        ])),
    url(r'^(?P<view_name>index_html|groups)$', redirect_old_urls),
    url(r'^(?P<concept_type>\w+)/(?P<concept_code>\d+)$', concept_redirect,
        name='concept_redirect'),
    url(r'^gemet/concept/$', old_concept_redirect,
        name='old_concept_redirect'),
    url(r'^gemet-backbone.html$', BackboneView.as_view(), name='backbone'),
    url(r'^gemet-backbone.rdf$', BackboneRDFView.as_view(),
        name='backbone_rdf'),
    url(r'^gemet-definitions.html$', DefinitionsView.as_view(),
        name='definitions'),
    url(r'^gemet-groups.html$', GemetGroupsView.as_view(),
        name='gemet-groups'),
    url(r'^gemet-relations.html$', GemetRelationsView.as_view(),
        name='gemet-relations'),
    url(r'^gemetThesaurus$', GemetThesaurus.as_view(), name='gemetThesaurus'),
)
